### ISSUE TITLE
more pictures

### ISSUE THREAD

**Issue by psychotik2k3** [muxa/ox-cnc#1]
hi do you have more pictures of your cnc ??
about your fences ?
and how your wastebord is places because it seems it's over the frame at the front isn't it ?
the bel tensionner how did you manage to make them work ??? do the screw goes into the aluminium profile or does it push on an already inserted screw ?
thanks

**Comment by muxa** [comment]
hi, just added more pictures and descriptions. hope it helps. let me know if you need more info.
